image: ubuntu:18.04

before_script:
  - apt-get update
  # needed to download NuGet
  - apt-get install -y curl

stages:
  - build
  - test

stockmono_build:
  stage: build
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y nuget mono-complete mono-xbuild fsharp

    - time (./configure.sh && make && make install)
    # so that we log the version of nuget for when it works
    - make nuget

stockmono_test:
  stage: test
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y nuget mono-complete mono-xbuild fsharp

    - time (apt-get install -y nunit-console &&
            ./configure.sh &&
            make &&
            make check)

newmono_build:
  stage: build
  script:
    # required by apt-key
    - apt install -y gnupg2
    # required by apt-update when pulling from mono-project.com
    - apt install -y ca-certificates

    # taken from http://www.mono-project.com/download/stable/#download-lin
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    - echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list
    - apt update
    - apt install -y mono-devel fsharp

    - time (./configure.sh && make && make install)
    # so that we log the version of nuget for when it works
    - make nuget

newmono_test:
  stage: test
  script:
    # required by apt-key
    - apt install -y gnupg2
    # required by apt-update when pulling from mono-project.com
    - apt install -y ca-certificates

    # taken from http://www.mono-project.com/download/stable/#download-lin
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    - echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list
    - apt update
    - apt install -y mono-devel fsharp
    - apt install -y nunit-console

    - time (./configure.sh && make && make check)

